//! Classic PCAP file reader and writer.
//!
//! Implemented directly against the file format instead of going through the system
//! capture library, for three reasons:
//!
//! 1. **Testability.** Golden PCAP fixtures can be generated by the workspace itself, so
//!    the test suite never needs a capture driver, administrator rights or a live network.
//! 2. **Portability.** The same reader works on Android and in headless CI where no
//!    libpcap exists.
//! 3. **Honesty about formats.** PCAPNG is a different container. This module detects it
//!    and reports a precise error rather than silently returning zero packets.
//!
//! Reference: the classic `pcap` savefile format (24-byte global header, 16-byte packet
//! headers). Both byte orders and both timestamp precisions are supported.

use std::fs::File;
use std::io::{BufReader, BufWriter, Read, Seek, SeekFrom, Write};
use std::path::Path;

use sentinel_common::error::{UserFacing, UserMessage};

/// Magic number of a microsecond-resolution capture file.
const MAGIC_USEC: u32 = 0xa1b2_c3d4;
/// Magic number of a nanosecond-resolution capture file.
const MAGIC_NSEC: u32 = 0xa1b2_3c4d;
/// Magic number of the PCAPNG block-based container format.
const MAGIC_PCAPNG: u32 = 0x0a0d_0d0a;

/// Length of the classic PCAP global header.
const GLOBAL_HEADER_LEN: usize = 24;
/// Length of the classic PCAP per-packet header.
const PACKET_HEADER_LEN: usize = 16;

/// Link-layer type for Ethernet, as stored in the file header.
pub const LINKTYPE_ETHERNET: u32 = 1;
/// Link-layer type for raw IPv4, as stored in the file header.
pub const LINKTYPE_IPV4: u32 = 228;
/// Link-layer type for raw IPv6, as stored in the file header.
pub const LINKTYPE_IPV6: u32 = 229;

/// A PCAP file failure.
#[derive(Debug, thiserror::Error)]
pub enum PcapFileError {
    /// The file could not be opened or read.
    #[error("could not access the capture file: {0}")]
    Io(String),

    /// The file does not start with a known magic number.
    #[error("not a PCAP file (unrecognized magic number 0x{0:08x})")]
    BadMagic(u32),

    /// The file uses a container format this reader does not support.
    #[error("this is a {0} file; convert it to classic PCAP first")]
    UnsupportedFormat(&'static str),

    /// A field holds a value that cannot be represented.
    #[error("capture file contains an invalid value: {field} = {value}")]
    InvalidField {
        /// Field name.
        field: &'static str,
        /// Offending value.
        value: u64,
    },

    /// A packet record claims more bytes than the file contains.
    #[error("capture file is truncated inside a packet record")]
    TruncatedPacket,

    /// Writing failed.
    #[error("could not write the capture file: {0}")]
    Write(String),
}

impl UserFacing for PcapFileError {
    fn user_message(&self) -> UserMessage {
        match self {
            PcapFileError::BadMagic(magic) => UserMessage::new(
                "This file is not a PCAP capture",
                "Sentinel could not recognise the capture file format.",
            )
            .with_hint("Confirm the file was not renamed or truncated during transfer.")
            .with_hint("Only classic PCAP is read directly. Convert PCAPNG with: editcap -F pcap in.pcapng out.pcap")
            .with_details(format!("unrecognized magic number 0x{magic:08x}")),
            PcapFileError::UnsupportedFormat(name) => UserMessage::new(
                "Unsupported capture format",
                format!("Sentinel reads classic PCAP files; this file is {name}."),
            )
            .with_hint("Convert it first: editcap -F pcap input.pcapng output.pcap  (editcap ships with Wireshark)"),
            PcapFileError::Io(details) => UserMessage::new(
                "Sentinel could not open this capture file",
                "The file may be missing, locked by another application, or outside your permission scope.",
            )
            .with_details(details.clone()),
            PcapFileError::InvalidField { field, value } => UserMessage::new(
                "This capture file is damaged",
                format!("The header field `{field}` holds an unusable value ({value})."),
            )
            .with_hint("Open the file in Wireshark to confirm, then re-export it as classic PCAP."),
            PcapFileError::TruncatedPacket => UserMessage::new(
                "This capture file ends unexpectedly",
                "The final packet record is incomplete, which usually means the capture was interrupted.",
            )
            .with_hint("Sentinel analysed every complete packet before the end of the file.")
            .with_hint("Use editcap to repair or trim the file, then analyse it again."),
            PcapFileError::Write(details) => UserMessage::new(
                "Sentinel could not write the capture file",
                "The destination may be read-only or out of disk space.",
            )
            .with_details(details.clone()),
        }
    }
}

/// Byte order of a capture file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Endian {
    /// Little-endian, as written by every current platform.
    Little,
    /// Big-endian, written by older or cross-architecture tools.
    Big,
}

impl Endian {
    /// Reads a `u32` in this byte order.
    fn u32(self, bytes: [u8; 4]) -> u32 {
        match self {
            Endian::Little => u32::from_le_bytes(bytes),
            Endian::Big => u32::from_be_bytes(bytes),
        }
    }

    /// Writes a `u32` in this byte order.
    fn write_u32(self, out: &mut [u8], value: u32) {
        out.copy_from_slice(&match self {
            Endian::Little => value.to_le_bytes(),
            Endian::Big => value.to_be_bytes(),
        });
    }

    /// Writes a `u16` in this byte order.
    fn write_u16(self, out: &mut [u8], value: u16) {
        out.copy_from_slice(&match self {
            Endian::Little => value.to_le_bytes(),
            Endian::Big => value.to_be_bytes(),
        });
    }
}

/// Timestamp resolution declared by the file header.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TimestampPrecision {
    /// One tick is one microsecond.
    Microseconds,
    /// One tick is one nanosecond.
    Nanoseconds,
}

impl TimestampPrecision {
    /// Ticks per second for this resolution.
    const fn per_second(self) -> u64 {
        match self {
            TimestampPrecision::Microseconds => 1_000_000,
            TimestampPrecision::Nanoseconds => 1_000_000_000,
        }
    }

    /// Converts a sub-second tick count to whole microseconds.
    ///
    /// Sub-microsecond remainders are truncated: Sentinel stores microsecond timestamps
    /// everywhere, so a nanosecond capture loses no information Sentinel would have used.
    const fn sub_second_to_micros(self, ticks: u64) -> u64 {
        ticks.saturating_mul(1_000_000) / self.per_second()
    }

    /// Converts whole microseconds to ticks of this resolution.
    const fn micros_to_ticks(self, micros: u64) -> u64 {
        micros.saturating_mul(self.per_second()) / 1_000_000
    }
}

/// File byte order, as reported to callers.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FileEndian {
    /// Little-endian file.
    Little,
    /// Big-endian file.
    Big,
}

/// The parsed global header of a capture file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PcapHeader {
    /// Link-layer type shared by every packet in the file.
    pub link_type: u32,
    /// Timestamp resolution.
    pub precision: TimestampPrecision,
    /// File byte order.
    pub endian: FileEndian,
}

impl PcapHeader {
    /// True when the file holds Ethernet frames, which is what the decoder expects.
    #[must_use]
    pub const fn is_ethernet(&self) -> bool {
        self.link_type == LINKTYPE_ETHERNET
    }
}

/// One packet record read from a capture file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PcapPacket {
    /// Capture timestamp in microseconds since the Unix epoch.
    pub timestamp_us: u64,
    /// Bytes on the wire.
    pub original_len: u32,
    /// Bytes present in the record.
    pub captured_len: u32,
    /// Frame bytes.
    pub data: Vec<u8>,
}

/// Streaming reader for classic PCAP files.
///
/// Owns a buffered handle and never loads a whole capture into memory, so a multi-gigabyte
/// file can be analysed with bounded memory.
pub struct PcapReader<R: Read = File> {
    inner: BufReader<R>,
    header: PcapHeader,
    endian: Endian,
    precision: TimestampPrecision,
    packets_read: u64,
}

impl PcapReader<File> {
    /// Opens a capture file and reads its global header.
    ///
    /// # Errors
    /// Returns [`PcapFileError`] when the file is missing, unreadable, PCAPNG, or has an
    /// unrecognized magic number.
    pub fn open(path: impl AsRef<Path>) -> Result<Self, PcapFileError> {
        let file = File::open(path.as_ref()).map_err(|err| PcapFileError::Io(err.to_string()))?;
        Self::from_reader(file)
    }
}

impl<R: Read> PcapReader<R> {
    /// Reads a capture from any reader.
    ///
    /// # Errors
    /// Returns [`PcapFileError`] for malformed or unsupported files.
    pub fn from_reader(reader: R) -> Result<Self, PcapFileError> {
        let mut inner = BufReader::new(reader);
        let mut magic_bytes = [0u8; 4];
        inner
            .read_exact(&mut magic_bytes)
            .map_err(|err| PcapFileError::Io(format!("reading file header: {err}")))?;

        // A writer stores 0xa1b2c3d4 in its own byte order, so reading the first four
        // bytes as a little-endian word identifies both cases at once:
        //   d4 c3 b2 a1 -> 0xa1b2c3d4 -> little-endian writer
        //   a1 b2 c3 d4 -> 0xd4c3b2a1 -> big-endian writer
        let as_le = u32::from_le_bytes(magic_bytes);
        let (endian, precision) = match as_le {
            MAGIC_USEC => (Endian::Little, TimestampPrecision::Microseconds),
            MAGIC_NSEC => (Endian::Little, TimestampPrecision::Nanoseconds),
            other if other.swap_bytes() == MAGIC_USEC => {
                (Endian::Big, TimestampPrecision::Microseconds)
            }
            other if other.swap_bytes() == MAGIC_NSEC => {
                (Endian::Big, TimestampPrecision::Nanoseconds)
            }
            _ if as_le == MAGIC_PCAPNG => return Err(PcapFileError::UnsupportedFormat("PCAPNG")),
            _ => return Err(PcapFileError::BadMagic(as_le)),
        };

        // version_major(2) version_minor(2) thiszone(4) sigfigs(4) snaplen(4) network(4)
        let mut rest = [0u8; GLOBAL_HEADER_LEN - 4];
        inner
            .read_exact(&mut rest)
            .map_err(|err| PcapFileError::Io(format!("reading file header: {err}")))?;

        let header = PcapHeader {
            link_type: endian.u32([rest[16], rest[17], rest[18], rest[19]]),
            precision,
            endian: match endian {
                Endian::Little => FileEndian::Little,
                Endian::Big => FileEndian::Big,
            },
        };

        Ok(Self {
            inner,
            header,
            endian,
            precision,
            packets_read: 0,
        })
    }

    /// The file's global header.
    #[must_use]
    pub const fn header(&self) -> PcapHeader {
        self.header
    }

    /// Number of packets read so far.
    #[must_use]
    pub const fn packets_read(&self) -> u64 {
        self.packets_read
    }

    /// Reads the next packet, or `None` at a clean end of file.
    ///
    /// # Errors
    /// Returns [`PcapFileError::TruncatedPacket`] when the final record is incomplete, so a
    /// partially written capture is reported rather than appearing to have ended cleanly.
    pub fn next_packet(&mut self) -> Result<Option<PcapPacket>, PcapFileError> {
        let mut packet_header = [0u8; PACKET_HEADER_LEN];
        let mut filled = 0usize;

        while filled < PACKET_HEADER_LEN {
            match self.inner.read(&mut packet_header[filled..]) {
                Ok(0) => {
                    if filled == 0 {
                        return Ok(None);
                    }
                    return Err(PcapFileError::TruncatedPacket);
                }
                Ok(read) => filled += read,
                Err(err) => return Err(PcapFileError::Io(err.to_string())),
            }
        }

        let seconds = self.endian.u32([
            packet_header[0],
            packet_header[1],
            packet_header[2],
            packet_header[3],
        ]);
        let sub_second = self.endian.u32([
            packet_header[4],
            packet_header[5],
            packet_header[6],
            packet_header[7],
        ]);
        let captured_len = self.endian.u32([
            packet_header[8],
            packet_header[9],
            packet_header[10],
            packet_header[11],
        ]);
        let original_len = self.endian.u32([
            packet_header[12],
            packet_header[13],
            packet_header[14],
            packet_header[15],
        ]);

        let mut data = vec![0u8; captured_len as usize];
        self.inner
            .read_exact(&mut data)
            .map_err(|err| PcapFileError::Io(format!("reading packet payload: {err}")))?;

        self.packets_read += 1;
        Ok(Some(PcapPacket {
            timestamp_us: u64::from(seconds)
                .saturating_mul(1_000_000)
                .saturating_add(self.precision.sub_second_to_micros(u64::from(sub_second))),
            original_len,
            captured_len,
            data,
        }))
    }

    /// Iterates over every remaining packet.
    ///
    /// # Errors
    /// Propagates the first read failure, including truncation.
    pub fn packets(&mut self) -> PacketIter<'_, R> {
        PacketIter { reader: self }
    }
}

/// Iterator over packets in a capture file.
pub struct PacketIter<'a, R: Read> {
    reader: &'a mut PcapReader<R>,
}

impl<R: Read> Iterator for PacketIter<'_, R> {
    type Item = Result<PcapPacket, PcapFileError>;

    fn next(&mut self) -> Option<Self::Item> {
        self.reader.next_packet().transpose()
    }
}

/// Writes a classic PCAP file.
///
/// Used for exports, evidence bundles and generating deterministic test fixtures.
pub struct PcapWriter<W: Write = File> {
    inner: BufWriter<W>,
    link_type: u32,
    snaplen: u32,
}

/// Builds a little-endian, microsecond-resolution global header.
fn build_global_header(snaplen: u32, link_type: u32) -> [u8; GLOBAL_HEADER_LEN] {
    let endian = Endian::Little;
    let mut header = [0u8; GLOBAL_HEADER_LEN];
    endian.write_u32(&mut header[0..4], MAGIC_USEC);
    endian.write_u16(&mut header[4..6], 2); // version major
    endian.write_u16(&mut header[6..8], 4); // version minor
    endian.write_u32(&mut header[8..12], 0); // GMT offset
    endian.write_u32(&mut header[12..16], 0); // timestamp accuracy
    endian.write_u32(&mut header[16..20], snaplen);
    endian.write_u32(&mut header[20..24], link_type);
    header
}

impl PcapWriter<File> {
    /// Creates a file-backed writer, emitting the global header immediately.
    ///
    /// # Errors
    /// Returns [`PcapFileError`] when the destination cannot be created or written.
    pub fn create(
        path: impl AsRef<Path>,
        link_type: u32,
        snaplen: u32,
    ) -> Result<Self, PcapFileError> {
        let file =
            File::create(path.as_ref()).map_err(|err| PcapFileError::Write(err.to_string()))?;
        Self::from_writer(file, link_type, snaplen)
    }

    /// Discards all written records and restarts the file, re-emitting the global header.
    ///
    /// The file is truncated first. Seeking alone would leave the tail of a longer previous
    /// run in place, producing a file whose remaining bytes a reader would try to parse as a
    /// packet header.
    ///
    /// # Errors
    /// Returns [`PcapFileError`] when the file cannot be truncated, rewound or written.
    pub fn restart(&mut self) -> Result<(), PcapFileError> {
        self.flush()?;
        let file = self.inner.get_mut();
        file.set_len(0)
            .map_err(|err| PcapFileError::Write(err.to_string()))?;
        file.seek(SeekFrom::Start(0))
            .map_err(|err| PcapFileError::Write(err.to_string()))?;
        self.write_global_header()
    }
}

impl<W: Write> PcapWriter<W> {
    /// Creates a writer around any writable sink, emitting the global header.
    ///
    /// # Errors
    /// Returns [`PcapFileError`] when the header cannot be written.
    pub fn from_writer(writer: W, link_type: u32, snaplen: u32) -> Result<Self, PcapFileError> {
        let mut inner = BufWriter::new(writer);
        inner
            .write_all(&build_global_header(snaplen, link_type))
            .map_err(|err| PcapFileError::Write(err.to_string()))?;
        Ok(Self {
            inner,
            link_type,
            snaplen,
        })
    }

    /// Re-emits the global header at the current position.
    ///
    /// # Errors
    /// Returns [`PcapFileError`] when the header cannot be written.
    pub fn write_global_header(&mut self) -> Result<(), PcapFileError> {
        let header = build_global_header(self.snaplen, self.link_type);
        self.inner
            .write_all(&header)
            .map_err(|err| PcapFileError::Write(err.to_string()))
    }

    /// Appends one packet record.
    ///
    /// # Errors
    /// Returns [`PcapFileError`] when the record cannot be written.
    pub fn write_packet(&mut self, timestamp_us: u64, data: &[u8]) -> Result<(), PcapFileError> {
        let length = u32::try_from(data.len()).map_err(|_| PcapFileError::InvalidField {
            field: "packet length",
            value: data.len() as u64,
        })?;

        let precision = TimestampPrecision::Microseconds;
        let seconds = u32::try_from(timestamp_us / 1_000_000).unwrap_or(u32::MAX);
        let sub_second =
            u32::try_from(precision.micros_to_ticks(timestamp_us % 1_000_000)).unwrap_or(u32::MAX);

        let mut header = [0u8; PACKET_HEADER_LEN];
        Endian::Little.write_u32(&mut header[0..4], seconds);
        Endian::Little.write_u32(&mut header[4..8], sub_second);
        Endian::Little.write_u32(&mut header[8..12], length);
        Endian::Little.write_u32(&mut header[12..16], length);

        self.inner
            .write_all(&header)
            .map_err(|err| PcapFileError::Write(err.to_string()))?;
        self.inner
            .write_all(data)
            .map_err(|err| PcapFileError::Write(err.to_string()))?;
        Ok(())
    }

    /// Flushes buffered data to the underlying sink.
    ///
    /// # Errors
    /// Returns [`PcapFileError`] when the flush fails.
    pub fn flush(&mut self) -> Result<(), PcapFileError> {
        self.inner
            .flush()
            .map_err(|err| PcapFileError::Write(err.to_string()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A minimal Ethernet frame: destination, source, EtherType, then padding.
    fn sample_frame() -> Vec<u8> {
        let mut frame = Vec::with_capacity(60);
        frame.extend_from_slice(&[0xff; 6]);
        frame.extend_from_slice(&[0x00, 0x11, 0x22, 0x33, 0x44, 0x55]);
        frame.extend_from_slice(&0x0806u16.to_be_bytes()); // ARP
        frame.extend_from_slice(&[0u8; 18]);
        frame
    }

    /// Writes raw bytes to a temporary file for byte-order and precision fixtures.
    fn write_raw(bytes: &[u8]) -> tempfile::NamedTempFile {
        let file = tempfile::NamedTempFile::new().expect("temp file");
        std::fs::write(file.path(), bytes).expect("write fixture");
        file
    }

    #[test]
    fn round_trips_a_capture() {
        let temp = tempfile::tempdir().expect("temp dir");
        let path = temp.path().join("out.pcap");

        {
            let mut writer =
                PcapWriter::create(&path, LINKTYPE_ETHERNET, 65_536).expect("create writer");
            let frame = sample_frame();
            writer
                .write_packet(1_735_689_600_000_000, &frame)
                .expect("write first");
            writer
                .write_packet(1_735_689_600_500_000, &frame)
                .expect("write second");
            writer.flush().expect("flush");
        }

        let mut reader = PcapReader::open(&path).expect("open reader");
        assert_eq!(reader.header().link_type, LINKTYPE_ETHERNET);
        assert!(reader.header().is_ethernet());
        assert_eq!(reader.header().precision, TimestampPrecision::Microseconds);
        assert_eq!(reader.header().endian, FileEndian::Little);

        let first = reader
            .next_packet()
            .expect("read first")
            .expect("packet present");
        assert_eq!(first.timestamp_us, 1_735_689_600_000_000);
        assert_eq!(first.data, sample_frame());
        assert_eq!(first.captured_len as usize, sample_frame().len());
        assert_eq!(first.original_len as usize, sample_frame().len());

        let second = reader
            .next_packet()
            .expect("read second")
            .expect("packet present");
        assert_eq!(second.timestamp_us, 1_735_689_600_500_000);
        assert!(reader.next_packet().expect("read third").is_none());
        assert_eq!(reader.packets_read(), 2);
    }

    #[test]
    fn iteration_visits_every_packet() {
        let temp = tempfile::tempdir().expect("temp dir");
        let path = temp.path().join("iterate.pcap");
        {
            let mut writer = PcapWriter::create(&path, LINKTYPE_ETHERNET, 1500).expect("create");
            let frame = sample_frame();
            for index in 0..5 {
                writer
                    .write_packet(1_000_000 + index * 1_000_000, &frame)
                    .expect("write");
            }
            writer.flush().expect("flush");
        }

        let mut reader = PcapReader::open(&path).expect("open");
        let packets = reader
            .packets()
            .collect::<Result<Vec<_>, _>>()
            .expect("iterate cleanly");
        assert_eq!(packets.len(), 5);
    }

    #[test]
    fn rejects_pcapng_with_a_conversion_hint() {
        let file = write_raw(&MAGIC_PCAPNG.to_le_bytes());
        let Err(err) = PcapReader::open(file.path()) else {
            panic!("pcapng must be rejected")
        };
        assert!(matches!(err, PcapFileError::UnsupportedFormat("PCAPNG")));
        let message = UserFacing::user_message(&err).to_plain_text();
        assert!(
            message.contains("editcap"),
            "hint should name the converter: {message}"
        );
    }

    #[test]
    fn rejects_unknown_magic() {
        // Bytes de ad be ef read little-endian as 0xefbeadde.
        let file = write_raw(&[0xde, 0xad, 0xbe, 0xef]);
        let Err(err) = PcapReader::open(file.path()) else {
            panic!("garbage must be rejected")
        };
        assert!(matches!(err, PcapFileError::BadMagic(0xefbe_adde)));
    }

    #[test]
    fn reports_truncated_final_packet() {
        let temp = tempfile::tempdir().expect("temp dir");
        let path = temp.path().join("truncated.pcap");
        {
            let mut writer = PcapWriter::create(&path, LINKTYPE_ETHERNET, 1500).expect("create");
            writer
                .write_packet(1_000_000, &sample_frame())
                .expect("write");
            writer.flush().expect("flush");
        }
        // Append a packet header that promises more payload than the file contains.
        let mut file = std::fs::OpenOptions::new()
            .append(true)
            .open(&path)
            .expect("reopen");
        let mut lying_header = [0u8; PACKET_HEADER_LEN];
        lying_header[8..12].copy_from_slice(&1000u32.to_le_bytes());
        lying_header[12..16].copy_from_slice(&1000u32.to_le_bytes());
        file.write_all(&lying_header).expect("append");

        let mut reader = PcapReader::open(&path).expect("open");
        reader
            .next_packet()
            .expect("first packet reads")
            .expect("first packet present");
        let err = reader
            .next_packet()
            .expect_err("truncation must be reported");
        assert!(matches!(
            err,
            PcapFileError::Io(_) | PcapFileError::TruncatedPacket
        ));
    }

    #[test]
    fn reads_big_endian_files() {
        let mut bytes = Vec::new();
        // A big-endian writer stores 0xa1b2c3d4 as a1 b2 c3 d4.
        bytes.extend_from_slice(&MAGIC_USEC.to_be_bytes());
        bytes.extend_from_slice(&2u16.to_be_bytes());
        bytes.extend_from_slice(&4u16.to_be_bytes());
        bytes.extend_from_slice(&0u32.to_be_bytes());
        bytes.extend_from_slice(&0u32.to_be_bytes());
        bytes.extend_from_slice(&65_536u32.to_be_bytes());
        bytes.extend_from_slice(&LINKTYPE_ETHERNET.to_be_bytes());
        bytes.extend_from_slice(&1_735_689_600u32.to_be_bytes());
        bytes.extend_from_slice(&123_456u32.to_be_bytes());
        bytes.extend_from_slice(&4u32.to_be_bytes());
        bytes.extend_from_slice(&4u32.to_be_bytes());
        bytes.extend_from_slice(&[0xde, 0xad, 0xbe, 0xef]);
        let file = write_raw(&bytes);

        let mut reader = PcapReader::open(file.path()).expect("open big-endian file");
        assert_eq!(reader.header().endian, FileEndian::Big);
        let packet = reader.next_packet().expect("read").expect("packet present");
        assert_eq!(packet.timestamp_us, 1_735_689_600_123_456);
        assert_eq!(packet.data, vec![0xde, 0xad, 0xbe, 0xef]);
    }

    #[test]
    fn nanosecond_files_convert_to_microseconds() {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&MAGIC_NSEC.to_le_bytes());
        bytes.extend_from_slice(&2u16.to_le_bytes());
        bytes.extend_from_slice(&4u16.to_le_bytes());
        bytes.extend_from_slice(&0u32.to_le_bytes());
        bytes.extend_from_slice(&0u32.to_le_bytes());
        bytes.extend_from_slice(&65_536u32.to_le_bytes());
        bytes.extend_from_slice(&LINKTYPE_ETHERNET.to_le_bytes());
        bytes.extend_from_slice(&2u32.to_le_bytes()); // 2 seconds
        bytes.extend_from_slice(&500_000u32.to_le_bytes()); // 500000 ns = 500 us
        bytes.extend_from_slice(&1u32.to_le_bytes());
        bytes.extend_from_slice(&1u32.to_le_bytes());
        bytes.push(0xab);
        let file = write_raw(&bytes);

        let mut reader = PcapReader::open(file.path()).expect("open");
        assert_eq!(reader.header().precision, TimestampPrecision::Nanoseconds);
        let packet = reader.next_packet().expect("read").expect("packet present");
        assert_eq!(packet.timestamp_us, 2_000_500);
    }

    #[test]
    fn restart_discards_previous_records() {
        let temp = tempfile::tempdir().expect("temp dir");
        let path = temp.path().join("restart.pcap");

        let mut writer = PcapWriter::create(&path, LINKTYPE_ETHERNET, 1500).expect("create");
        for index in 0..3 {
            writer
                .write_packet(1_000_000 * (index + 1), &sample_frame())
                .expect("write");
        }
        writer.flush().expect("flush");

        // A shorter second run must not leave the first run's tail behind.
        writer.restart().expect("restart");
        writer
            .write_packet(9_000_000, &sample_frame())
            .expect("write after restart");
        writer.flush().expect("flush");

        let mut reader = PcapReader::open(&path).expect("open");
        assert_eq!(
            reader
                .next_packet()
                .expect("read")
                .expect("packet")
                .timestamp_us,
            9_000_000
        );
        assert!(
            reader.next_packet().expect("end").is_none(),
            "no stale records may survive"
        );
    }

    #[test]
    fn missing_file_reports_an_io_error() {
        let Err(err) = PcapReader::open("definitely-missing-file.pcap") else {
            panic!("missing file must fail")
        };
        assert!(matches!(err, PcapFileError::Io(_)));
        assert!(!UserFacing::user_message(&err).title.is_empty());
    }
}
